name: test
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests
    runs-on: self-hosted
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm install 

      - name: Run tests
        run: npm test